# Generated by Django 5.2.17 on 2026-09-25 17:06

import common.timezones
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('continent', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=64, validators=[common.timezones.validate_iana_timezone])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='parent_created_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='parent_email_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_utc', models.DateTimeField()),
                ('end_time_utc', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mentors.mentor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bookings.parent')),
            ],
            options={
                'ordering': ['start_time_utc'],
                'indexes': [models.Index(fields=['mentor', 'start_time_utc'], name='appt_mentor_start_idx'), models.Index(fields=['parent', 'start_time_utc'], name='appt_parent_start_idx'), models.Index(fields=['status', 'start_time_utc'], name='appt_status_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time_utc__gt', models.F('start_time_utc'))), name='appointment_end_after_start')],
            },
        ),
    ]
