# Generated by Django 5.2.17 on 2026-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
