# Generated by Django 5.2.17 on 2026-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_request_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
