# Generated by Django 5.2.17 on 2026-09-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('mentor_notification', 'Mentor notification')], max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_emails', to='bookings.appointment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'recipient', 'email_type'), name='outbox_appointment_recipient_type_uniq')],
            },
        ),
    ]
