# Generated by Django 5.2.17 on 2026-09-26 08:03

import common.timezones
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('parent_name', models.CharField(max_length=160)),
                ('parent_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('preferred_start_utc', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64, validators=[common.timezones.validate_iana_timezone])),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['preferred_start_utc'], name='support_call_start_idx')],
            },
        ),
    ]
