# Generated by Django 5.2.17 on 2026-09-25 17:06

import common.timezones
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('continent', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64, validators=[common.timezones.validate_iana_timezone])),
                ('working_hours', models.JSONField(default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active', 'timezone'], name='mentor_active_tz_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='mentor_email_ci_uniq')],
            },
        ),
    ]
