# Generated by Django 5.2.17 on 2026-09-26 09:18

import common.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_alter_mentor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='timezone',
            field=models.CharField(max_length=64, validators=[common.timezones.validate_iana_timezone]),
        ),
    ]
